name: Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: lower
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/${{ steps.lower.outputs.lowercase }}:${{ github.run_number }},ghcr.io/${{ steps.lower.outputs.lowercase }}:latest